#!/usr/bin/env bash

# One worker draining a shared queue of sites, running ecLand on each.
#
# WHY A QUEUE RATHER THAN A SLICE PER WORKER. Runtime scales with record
# length, and the 170 PLUMBER2 sites run from 1 to 21 years (1040 site-years in
# total, median 4). Hand each worker a fixed slice and the finish time is set by
# whichever worker draws the worst combination; draining one shared queue
# instead means a worker that finishes a 1-year site immediately takes another,
# so the makespan falls to max(total/N, longest single site) -- 2.26 h at the
# default 25 workers, within 1% of the ideal 2.24 h, against a 1.13 h floor set
# by the longest record.
#
# WHY THIS IS ALSO SAFER THAN A SLICE. Each site is claimed, run and recorded
# individually:
#
#   - the claim is an mkdir, which is atomic on POSIX and on Lustre, so exactly
#     one worker on one node can win a given site, with no lock and no server;
#   - the run is guarded by `if ! ...`, which `set -e` deliberately ignores, so
#     a site that fails costs that site and nothing else. Running a slice under
#     `set -eu` without this guard loses every remaining site in the slice to
#     one bad one;
#   - a status file per site makes the whole thing resumable: a re-submitted
#     array skips what is done, and retrying the failures is
#     `grep -lx FAILED status/* | xargs rm` and submit again.
#
# A worker interrupted mid-site (wall limit, node failure) leaves a claim with
# no status. That is deliberate: the submitter sweeps such claims before the
# next submission, so an interruption costs one site rather than a slice, and
# the site is retried. Note that a worker lives for the whole DRAIN, not for one
# site -- roughly total/N -- so the wall limit has to cover that, not just the
# longest record; see "WALL LIMIT" in submit_ecland_slurm.sh.
#
# This is the array-job counterpart to the LBATCH=true path in
# ecland_run_experiment.sh, which submits one job per site and caps itself at
# MAX_CONCURRENT=25 while a login-node poller waits on the whole set.
#
# DO NOT EDIT THIS FILE IN PLACE WHILE A JOB IS RUNNING IT. Bash reads a script
# lazily, so rewriting it under a live interpreter shifts the offsets it is about
# to read from; workers then lose whatever follows the loop they are inside. Edit
# a copy and `mv` it over this path instead -- a rename leaves running workers on
# the old inode, so they finish cleanly.
#
# Usage:
#   ecland_run_queue.sh -g GROUP -Q QUEUE_FILE -D RUN_ROOT -x ECLAND_MASTER
#                       [-t FORCING_TYPE] [-l NLOOP] [-n NAMELIST] [-R RETRIES]
#
# (C) Copyright 2026- ECMWF.
#
# Licensed under the Apache Licence Version 2.0:
# http://www.apache.org/licenses/LICENSE-2.0
#
# In applying this licence, ECMWF does not waive the privileges and immunities
# granted to it by virtue of its status as an intergovernmental organisation,
# nor does it submit to any jurisdiction.

set -u
set -o pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"

GROUP=""
QUEUE_FILE=""
RUN_ROOT=""
ECLAND_MASTER=""
FORCING_TYPE="insitu"
NLOOP=2
NAMELIST=""
RETRIES=1

usage() {
  sed -n '/^# Usage:/,/^# (C)/p' "${BASH_SOURCE[0]}" | sed 's/^#[[:space:]]\{0,1\}//'
}

while getopts ":hg:Q:D:x:t:l:n:R:" opt; do
  case "${opt}" in
    g) GROUP="${OPTARG}" ;;
    Q) QUEUE_FILE="${OPTARG}" ;;
    D) RUN_ROOT="${OPTARG}" ;;
    x) ECLAND_MASTER="${OPTARG}" ;;
    t) FORCING_TYPE="${OPTARG}" ;;
    l) NLOOP="${OPTARG}" ;;
    n) NAMELIST="${OPTARG}" ;;
    R) RETRIES="${OPTARG}" ;;
    h) usage; exit 0 ;;
    \?) echo "ERROR: invalid option -${OPTARG}" >&2; usage >&2; exit 2 ;;
    :) echo "ERROR: option -${OPTARG} requires an argument" >&2; usage >&2; exit 2 ;;
  esac
done

for req in GROUP QUEUE_FILE RUN_ROOT ECLAND_MASTER; do
  [[ -n "${!req}" ]] || { echo "ERROR: -${req} is required" >&2; usage >&2; exit 2; }
done
[[ -f "${QUEUE_FILE}" ]] || { echo "ERROR: queue not found: ${QUEUE_FILE}" >&2; exit 1; }

STATUS_DIR="${RUN_ROOT}/status"
CLAIM_DIR="${RUN_ROOT}/claims"
LOG_DIR="${RUN_ROOT}/logs"
OUTPUT_DIR="${RUN_ROOT}/output"
WORKER="${SLURM_ARRAY_TASK_ID:-$$}"
WORK_DIR="${RUN_ROOT}/work/worker_${WORKER}"
mkdir -p "${STATUS_DIR}" "${CLAIM_DIR}" "${LOG_DIR}" "${OUTPUT_DIR}" "${WORK_DIR}"

n_ok=0; n_fail=0; n_skip=0
start=$(date +%s)
echo "worker ${WORKER} on $(hostname): draining $(grep -c . "${QUEUE_FILE}") sites from ${QUEUE_FILE}"

# The queue is read on FD 9, not stdin, and every child gets </dev/null. Both
# halves matter: `mpirun` drains the stdin it inherits, so with the queue on
# stdin a worker loses the rest of it to the first site it runs and exits after
# one -- measured, 30 workers completing exactly one site each. FD 9 puts the
# queue out of reach of anything a child does with descriptor 0, and </dev/null
# means a child that reads stdin gets EOF rather than another worker's data.
while read -r -u 9 site; do
  [[ -n "${site}" ]] || continue
  [[ -f "${STATUS_DIR}/${site}" ]] && { n_skip=$((n_skip + 1)); continue; }

  # Atomic across every worker and node: exactly one mkdir can succeed.
  mkdir "${CLAIM_DIR}/${site}" 2>/dev/null || { n_skip=$((n_skip + 1)); continue; }
  echo "${SLURM_JOB_ID:-local} $(hostname) $(date -u +%FT%TZ)" > "${CLAIM_DIR}/${site}/owner"

  t0=$(date +%s)
  status="FAILED"
  attempt=0
  while [[ "${attempt}" -le "${RETRIES}" ]]; do
    attempt=$((attempt + 1))
    # `set -e` does not act on a command in an `if` condition, which is exactly
    # what keeps one failing site from taking the rest of the queue with it.
    if LBATCH=false "${SCRIPT_DIR}/ecland_run_experiment.sh" \
         -g "${GROUP}" \
         -t "${FORCING_TYPE}" \
         -s "${site}" \
         -x "${ECLAND_MASTER}" \
         -o "${OUTPUT_DIR}" \
         -w "${WORK_DIR}" \
         ${NAMELIST:+-n "${NAMELIST}"} \
         -l "${NLOOP}" </dev/null >> "${LOG_DIR}/${site}.log" 2>&1; then
      status="OK"
      break
    fi
    echo "attempt ${attempt} failed for ${site}" >> "${LOG_DIR}/${site}.log"
  done

  echo "${status}" > "${STATUS_DIR}/${site}"
  t1=$(date +%s)
  [[ "${status}" == "OK" ]] && n_ok=$((n_ok + 1)) || n_fail=$((n_fail + 1))
  echo "[$(date '+%H:%M:%S')] ${status} ${site} ($(( t1 - t0 ))s, attempt ${attempt})"
done 9< "${QUEUE_FILE}"

echo "worker ${WORKER} done in $(( $(date +%s) - start ))s: ${n_ok} ok, ${n_fail} failed, ${n_skip} skipped/claimed elsewhere"
